groups:
  - name: Blackbox
    rules:
      - alert: BlackboxProbeHttpFailure
        expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
        for: 5m
        labels:
          severity: critical
        annotations:
          identifier: "{{ $labels.instance }}"
          summary: "{{ $labels.name }} - {{ $labels.instance }} - HTTP failure"
          description: "HTTP status code is not 200-399."

      - alert: BlackboxProbeSlowHttp
        expr: avg_over_time(probe_http_duration_seconds[1m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          identifier: "{{ $labels.instance }}"
          summary: "{{ $labels.name }} - {{ $labels.instance }} - slow HTTP"
          description: "HTTP request took more than 1s."

      - alert: BlackboxSslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 5m
        labels:
          severity: warning
        annotations:
          identifier: "{{ $labels.instance }}"
          summary: "{{ $labels.name }} - {{ $labels.instance }} - SSL certificate will expire soon"
          description: "SSL certificate expires in 7 days."

      - alert: BlackboxSslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 2
        for: 5m
        labels:
          severity: critical
        annotations:
          identifier: "{{ $labels.instance }}"
          summary: "{{ $labels.name }} - {{ $labels.instance }} - SSL certificate will expire soon"
          description: "SSL certificate expires in 2 days."

      - alert: BlackboxSslCertificateExpired
        expr: probe_ssl_earliest_cert_expiry - time() <= 0
        for: 5m
        labels:
          severity: critical
        annotations:
          identifier: "{{ $labels.instance }}"
          summary: "{{ $labels.name }} - {{ $labels.instance }} - SSL certificate expired"
          description: "SSL certificate has expired."

      - alert: BlackboxProbeSlowPing
        expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          identifier: "{{ $labels.instance }}"
          summary: "{{ $labels.name }} - {{ $labels.instance }} - slow ping"
          description: "Ping took more than 1s."
