---
name: run-tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Test installer
        run: |
          cp .env.example .env
          ./autopilot install ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}
